//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPWA.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPWA.Common.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string _Translations {
            get {
                return ResourceManager.GetString("_Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string About_us {
            get {
                return ResourceManager.GetString("About_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account locked out.
        /// </summary>
        public static string Account_locked_out {
            get {
                return ResourceManager.GetString("Account_locked_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account settings and more.
        /// </summary>
        public static string Account_settings_and_more {
            get {
                return ResourceManager.GetString("Account_settings_and_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account types.
        /// </summary>
        public static string Account_types {
            get {
                return ResourceManager.GetString("Account_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account types.
        /// </summary>
        public static string AccountTypes {
            get {
                return ResourceManager.GetString("AccountTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account types management.
        /// </summary>
        public static string AccountTypesManagement {
            get {
                return ResourceManager.GetString("AccountTypesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add business unit.
        /// </summary>
        public static string Add_business_unit {
            get {
                return ResourceManager.GetString("Add_business_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add city.
        /// </summary>
        public static string Add_city {
            get {
                return ResourceManager.GetString("Add_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add company.
        /// </summary>
        public static string Add_company {
            get {
                return ResourceManager.GetString("Add_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add country.
        /// </summary>
        public static string Add_country {
            get {
                return ResourceManager.GetString("Add_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add currency.
        /// </summary>
        public static string Add_currency {
            get {
                return ResourceManager.GetString("Add_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to add an item.
        /// </summary>
        public static string Add_error {
            get {
                return ResourceManager.GetString("Add_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group.
        /// </summary>
        public static string Add_group {
            get {
                return ResourceManager.GetString("Add_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add language.
        /// </summary>
        public static string Add_language {
            get {
                return ResourceManager.GetString("Add_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add notification.
        /// </summary>
        public static string Add_notification {
            get {
                return ResourceManager.GetString("Add_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add role.
        /// </summary>
        public static string Add_role {
            get {
                return ResourceManager.GetString("Add_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added item.
        /// </summary>
        public static string Add_success {
            get {
                return ResourceManager.GetString("Add_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ticket.
        /// </summary>
        public static string Add_ticket {
            get {
                return ResourceManager.GetString("Add_ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add translation.
        /// </summary>
        public static string Add_translation {
            get {
                return ResourceManager.GetString("Add_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string Add_user {
            get {
                return ResourceManager.GetString("Add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All companies.
        /// </summary>
        public static string All_companies {
            get {
                return ResourceManager.GetString("All_companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api version.
        /// </summary>
        public static string Api_version {
            get {
                return ResourceManager.GetString("Api_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure.
        /// </summary>
        public static string Are_you_sure {
            get {
                return ResourceManager.GetString("Are you sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth settings.
        /// </summary>
        public static string Auth_settings {
            get {
                return ResourceManager.GetString("Auth_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPWA.
        /// </summary>
        public static string BPWA {
            get {
                return ResourceManager.GetString("BPWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast.
        /// </summary>
        public static string Broadcast {
            get {
                return ResourceManager.GetString("Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug.
        /// </summary>
        public static string Bug {
            get {
                return ResourceManager.GetString("Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business unit.
        /// </summary>
        public static string Business_unit {
            get {
                return ResourceManager.GetString("Business_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business unit must be selected.
        /// </summary>
        public static string Business_unit_must_be_selected {
            get {
                return ResourceManager.GetString("Business_unit_must_be_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business unit god mode.
        /// </summary>
        public static string BusinessUnitGodMode {
            get {
                return ResourceManager.GetString("BusinessUnitGodMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business unit roles management.
        /// </summary>
        public static string BusinessUnitRolesManagement {
            get {
                return ResourceManager.GetString("BusinessUnitRolesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bussiness units.
        /// </summary>
        public static string BusinessUnits {
            get {
                return ResourceManager.GetString("BusinessUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business units management.
        /// </summary>
        public static string BusinessUnitsManagement {
            get {
                return ResourceManager.GetString("BusinessUnitsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business unit users management.
        /// </summary>
        public static string BusinessUnitUsersManagement {
            get {
                return ResourceManager.GetString("BusinessUnitUsersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an option.
        /// </summary>
        public static string Choose_an_option {
            get {
                return ResourceManager.GetString("Choose_an_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities management.
        /// </summary>
        public static string CitiesManagement {
            get {
                return ResourceManager.GetString("CitiesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filters.
        /// </summary>
        public static string Clear_filters {
            get {
                return ResourceManager.GetString("Clear_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies management.
        /// </summary>
        public static string CompaniesManagement {
            get {
                return ResourceManager.GetString("CompaniesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company must be selected.
        /// </summary>
        public static string Company_must_be_selected {
            get {
                return ResourceManager.GetString("Company_must_be_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company users.
        /// </summary>
        public static string Company_users {
            get {
                return ResourceManager.GetString("Company_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company god mode.
        /// </summary>
        public static string CompanyGodMode {
            get {
                return ResourceManager.GetString("CompanyGodMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company roles management.
        /// </summary>
        public static string CompanyRolesManagement {
            get {
                return ResourceManager.GetString("CompanyRolesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company users management.
        /// </summary>
        public static string CompanyUsersManagement {
            get {
                return ResourceManager.GetString("CompanyUsersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrency failure.
        /// </summary>
        public static string Concurrency_failure {
            get {
                return ResourceManager.GetString("Concurrency_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration management.
        /// </summary>
        public static string ConfigurationManagement {
            get {
                return ResourceManager.GetString("ConfigurationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries management.
        /// </summary>
        public static string CountriesManagement {
            get {
                return ResourceManager.GetString("CountriesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies management.
        /// </summary>
        public static string CurrenciesManagement {
            get {
                return ResourceManager.GetString("CurrenciesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Current_password {
            get {
                return ResourceManager.GetString("Current_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default_error.
        /// </summary>
        public static string Default_error {
            get {
                return ResourceManager.GetString("Default_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to delete an item.
        /// </summary>
        public static string Delete_error {
            get {
                return ResourceManager.GetString("Delete_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted an item.
        /// </summary>
        public static string Delete_success {
            get {
                return ResourceManager.GetString("Delete_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying.
        /// </summary>
        public static string Displaying {
            get {
                return ResourceManager.GetString("Displaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistributionType.
        /// </summary>
        public static string DistributionType {
            get {
                return ResourceManager.GetString("DistributionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change currently selected business unit.
        /// </summary>
        public static string Do_you_want_to_change_currently_selected_business_unit {
            get {
                return ResourceManager.GetString("Do_you_want_to_change_currently_selected_business_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change currently selected company.
        /// </summary>
        public static string Do_you_want_to_change_currently_selected_company {
            get {
                return ResourceManager.GetString("Do_you_want_to_change_currently_selected_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate email.
        /// </summary>
        public static string Duplicate_email {
            get {
                return ResourceManager.GetString("Duplicate_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate role name.
        /// </summary>
        public static string Duplicate_role_name {
            get {
                return ResourceManager.GetString("Duplicate_role_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate user name.
        /// </summary>
        public static string Duplicate_user_name {
            get {
                return ResourceManager.GetString("Duplicate_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit account type.
        /// </summary>
        public static string Edit_account_type {
            get {
                return ResourceManager.GetString("Edit_account_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit business unit.
        /// </summary>
        public static string Edit_business_unit {
            get {
                return ResourceManager.GetString("Edit_business_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit city.
        /// </summary>
        public static string Edit_city {
            get {
                return ResourceManager.GetString("Edit_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit company.
        /// </summary>
        public static string Edit_company {
            get {
                return ResourceManager.GetString("Edit_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit country.
        /// </summary>
        public static string Edit_country {
            get {
                return ResourceManager.GetString("Edit_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit currency.
        /// </summary>
        public static string Edit_currency {
            get {
                return ResourceManager.GetString("Edit_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to edit an item.
        /// </summary>
        public static string Edit_error {
            get {
                return ResourceManager.GetString("Edit_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit group.
        /// </summary>
        public static string Edit_group {
            get {
                return ResourceManager.GetString("Edit_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit language.
        /// </summary>
        public static string Edit_language {
            get {
                return ResourceManager.GetString("Edit_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit role.
        /// </summary>
        public static string Edit_role {
            get {
                return ResourceManager.GetString("Edit_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully edited an item.
        /// </summary>
        public static string Edit_success {
            get {
                return ResourceManager.GetString("Edit_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit ticket.
        /// </summary>
        public static string Edit_ticket {
            get {
                return ResourceManager.GetString("Edit_ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit translation.
        /// </summary>
        public static string Edit_translation {
            get {
                return ResourceManager.GetString("Edit_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string Edit_user {
            get {
                return ResourceManager.GetString("Edit_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter translation for.
        /// </summary>
        public static string Enter_translation_for {
            get {
                return ResourceManager.GetString("Enter_translation_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change password.
        /// </summary>
        public static string Failed_to_change_password {
            get {
                return ResourceManager.GetString("Failed_to_change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update timezone.
        /// </summary>
        public static string Failed_to_update_timezone {
            get {
                return ResourceManager.GetString("Failed_to_update_timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        public static string Fatal {
            get {
                return ResourceManager.GetString("Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        public static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string First_name {
            get {
                return ResourceManager.GetString("First_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geolocations.
        /// </summary>
        public static string Geolocations {
            get {
                return ResourceManager.GetString("Geolocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to God mode.
        /// </summary>
        public static string GodMode {
            get {
                return ResourceManager.GetString("GodMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups management.
        /// </summary>
        public static string GroupsManagement {
            get {
                return ResourceManager.GetString("GroupsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indefinite.
        /// </summary>
        public static string Indefinite {
            get {
                return ResourceManager.GetString("Indefinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string Invalid_email {
            get {
                return ResourceManager.GetString("Invalid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid role name.
        /// </summary>
        public static string Invalid_role_name {
            get {
                return ResourceManager.GetString("Invalid_role_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string Invalid_token {
            get {
                return ResourceManager.GetString("Invalid_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name.
        /// </summary>
        public static string Invalid_user_name {
            get {
                return ResourceManager.GetString("Invalid_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string Invalid_username_or_password {
            get {
                return ResourceManager.GetString("Invalid_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages management.
        /// </summary>
        public static string LanguagesManagement {
            get {
                return ResourceManager.GetString("LanguagesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Last_name {
            get {
                return ResourceManager.GetString("Last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login already associated.
        /// </summary>
        public static string Login_already_associated {
            get {
                return ResourceManager.GetString("Login_already_associated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login not allowed.
        /// </summary>
        public static string Login_not_allowed {
            get {
                return ResourceManager.GetString("Login_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two factor authentication required.
        /// </summary>
        public static string Login_required_two_factor {
            get {
                return ResourceManager.GetString("Login_required_two_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs read.
        /// </summary>
        public static string LogsRead {
            get {
                return ResourceManager.GetString("LogsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine name.
        /// </summary>
        public static string MachineName {
            get {
                return ResourceManager.GetString("MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile version.
        /// </summary>
        public static string Mobile_version {
            get {
                return ResourceManager.GetString("Mobile_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More_pages.
        /// </summary>
        public static string More_pages {
            get {
                return ResourceManager.GetString("More_pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string My_profile {
            get {
                return ResourceManager.GetString("My_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string New_password {
            get {
                return ResourceManager.GetString("New_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password confirmation.
        /// </summary>
        public static string New_password_confirmation {
            get {
                return ResourceManager.GetString("New_password_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New record.
        /// </summary>
        public static string New_record {
            get {
                return ResourceManager.GetString("New_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No company is selected.
        /// </summary>
        public static string No_company_is_selected {
            get {
                return ResourceManager.GetString("No_company_is_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        public static string No_records_found {
            get {
                return ResourceManager.GetString("No_records_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification distribution type.
        /// </summary>
        public static string Notification_distribution_type {
            get {
                return ResourceManager.GetString("Notification_distribution_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification type.
        /// </summary>
        public static string Notification_type {
            get {
                return ResourceManager.GetString("Notification_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications management.
        /// </summary>
        public static string NotificationsManagement {
            get {
                return ResourceManager.GetString("NotificationsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number.
        /// </summary>
        public static string Page_number {
            get {
                return ResourceManager.GetString("Page_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmed.
        /// </summary>
        public static string Password_confirmed {
            get {
                return ResourceManager.GetString("Password_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password mismatch.
        /// </summary>
        public static string Password_mismatch {
            get {
                return ResourceManager.GetString("Password_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password requires_digit.
        /// </summary>
        public static string Password_requires_digit {
            get {
                return ResourceManager.GetString("Password_requires_digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password requires_lower.
        /// </summary>
        public static string Password_requires_lower {
            get {
                return ResourceManager.GetString("Password_requires_lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password requires_non_alphanumeric.
        /// </summary>
        public static string Password_requires_non_alphanumeric {
            get {
                return ResourceManager.GetString("Password_requires_non_alphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password requires_unique_chars.
        /// </summary>
        public static string Password_requires_unique_chars {
            get {
                return ResourceManager.GetString("Password_requires_unique_chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password requires_upper.
        /// </summary>
        public static string Password_requires_upper {
            get {
                return ResourceManager.GetString("Password_requires_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset link has been sent.
        /// </summary>
        public static string Password_reset_link_has_been_sent {
            get {
                return ResourceManager.GetString("Password_reset_link_has_been_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset link will be sent to user&apos;s email.
        /// </summary>
        public static string Password_reset_link_will_be_sent_to_users_email {
            get {
                return ResourceManager.GetString("Password_reset_link_will_be_sent_to_users_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password too short.
        /// </summary>
        public static string Password_too_short {
            get {
                return ResourceManager.GetString("Password_too_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string Passwords_do_not_match {
            get {
                return ResourceManager.GetString("Passwords_do_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string Please_wait {
            get {
                return ResourceManager.GetString("Please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been deleted.
        /// </summary>
        public static string Record_has_been_deleted {
            get {
                return ResourceManager.GetString("Record_has_been_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code redemption failed.
        /// </summary>
        public static string Recovery_code_redemption_failed {
            get {
                return ResourceManager.GetString("Recovery_code_redemption_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        public static string Regular {
            get {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Required_field {
            get {
                return ResourceManager.GetString("Required_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string Reset_password {
            get {
                return ResourceManager.GetString("Reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles management.
        /// </summary>
        public static string RolesManagement {
            get {
                return ResourceManager.GetString("RolesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and continue.
        /// </summary>
        public static string Save_and_continue {
            get {
                return ResourceManager.GetString("Save_and_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search (Use &apos;%&apos; as a wildcard anywhere in the text).
        /// </summary>
        public static string Search_use_precent_as_a_wildcard_anywhere_in_text {
            get {
                return ResourceManager.GetString("Search_use_precent_as_a_wildcard_anywhere_in_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string Select_all {
            get {
                return ResourceManager.GetString("Select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select app claim.
        /// </summary>
        public static string Select_app_claim {
            get {
                return ResourceManager.GetString("Select_app_claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select business unit.
        /// </summary>
        public static string Select_business_unit {
            get {
                return ResourceManager.GetString("Select_business_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select city.
        /// </summary>
        public static string Select_city {
            get {
                return ResourceManager.GetString("Select_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select company.
        /// </summary>
        public static string Select_company {
            get {
                return ResourceManager.GetString("Select_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select country.
        /// </summary>
        public static string Select_country {
            get {
                return ResourceManager.GetString("Select_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select currency.
        /// </summary>
        public static string Select_currency {
            get {
                return ResourceManager.GetString("Select_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select group.
        /// </summary>
        public static string Select_group {
            get {
                return ResourceManager.GetString("Select_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string Select_language {
            get {
                return ResourceManager.GetString("Select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select notification distribution type.
        /// </summary>
        public static string Select_notification_distribution_type {
            get {
                return ResourceManager.GetString("Select_notification_distribution_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select notification type.
        /// </summary>
        public static string Select_notification_type {
            get {
                return ResourceManager.GetString("Select_notification_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select page size.
        /// </summary>
        public static string Select_page_size {
            get {
                return ResourceManager.GetString("Select_page_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select roles.
        /// </summary>
        public static string Select_roles {
            get {
                return ResourceManager.GetString("Select_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select system account type.
        /// </summary>
        public static string Select_system_account_type {
            get {
                return ResourceManager.GetString("Select_system_account_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ticket status.
        /// </summary>
        public static string Select_ticket_status {
            get {
                return ResourceManager.GetString("Select_ticket_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ticket type.
        /// </summary>
        public static string Select_ticket_type {
            get {
                return ResourceManager.GetString("Select_ticket_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user.
        /// </summary>
        public static string Select_user {
            get {
                return ResourceManager.GetString("Select_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Sign_in {
            get {
                return ResourceManager.GetString("Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single user.
        /// </summary>
        public static string SingleUser {
            get {
                return ResourceManager.GetString("SingleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed current business unit.
        /// </summary>
        public static string Successfully_changed_current_business_unit {
            get {
                return ResourceManager.GetString("Successfully_changed_current_business_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed current company.
        /// </summary>
        public static string Successfully_changed_current_company {
            get {
                return ResourceManager.GetString("Successfully_changed_current_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully changed password.
        /// </summary>
        public static string Successfully_changed_password {
            get {
                return ResourceManager.GetString("Successfully_changed_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System account type.
        /// </summary>
        public static string System_account_type {
            get {
                return ResourceManager.GetString("System_account_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System settings.
        /// </summary>
        public static string System_settings {
            get {
                return ResourceManager.GetString("System_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to change current business unit.
        /// </summary>
        public static string There_was_an_error_while_trying_to_change_current_business_unit {
            get {
                return ResourceManager.GetString("There_was_an_error_while_trying_to_change_current_business_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to change current company.
        /// </summary>
        public static string There_was_an_error_while_trying_to_change_current_company {
            get {
                return ResourceManager.GetString("There_was_an_error_while_trying_to_change_current_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket status.
        /// </summary>
        public static string Ticket_status {
            get {
                return ResourceManager.GetString("Ticket_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket type.
        /// </summary>
        public static string Ticket_type {
            get {
                return ResourceManager.GetString("Ticket_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets management.
        /// </summary>
        public static string TicketsManagement {
            get {
                return ResourceManager.GetString("TicketsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle business unit.
        /// </summary>
        public static string ToggleBusinessUnit {
            get {
                return ResourceManager.GetString("ToggleBusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle company.
        /// </summary>
        public static string ToggleCompany {
            get {
                return ResourceManager.GetString("ToggleCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations management.
        /// </summary>
        public static string TranslationsManagement {
            get {
                return ResourceManager.GetString("TranslationsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        public static string Trial {
            get {
                return ResourceManager.GetString("Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update role.
        /// </summary>
        public static string Update_role {
            get {
                return ResourceManager.GetString("Update role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ticket.
        /// </summary>
        public static string Update_ticket {
            get {
                return ResourceManager.GetString("Update_ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has password.
        /// </summary>
        public static string User_already_has_password {
            get {
                return ResourceManager.GetString("User_already_has_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already in role.
        /// </summary>
        public static string User_already_in_role {
            get {
                return ResourceManager.GetString("User_already_in_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User lockout not enabled.
        /// </summary>
        public static string User_lockout_not_enabled {
            get {
                return ResourceManager.GetString("User_lockout_not_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string User_name {
            get {
                return ResourceManager.GetString("User_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email.
        /// </summary>
        public static string User_name_or_email {
            get {
                return ResourceManager.GetString("User_name_or_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email invalid.
        /// </summary>
        public static string User_name_or_email_invalid {
            get {
                return ResourceManager.GetString("User_name_or_email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string User_not_found {
            get {
                return ResourceManager.GetString("User_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not in role.
        /// </summary>
        public static string User_not_in_role {
            get {
                return ResourceManager.GetString("User_not_in_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users management.
        /// </summary>
        public static string UsersManagement {
            get {
                return ResourceManager.GetString("UsersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        public static string Verbose {
            get {
                return ResourceManager.GetString("Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web version.
        /// </summary>
        public static string Web_version {
            get {
                return ResourceManager.GetString("Web_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete it.
        /// </summary>
        public static string Yes_delete_it {
            get {
                return ResourceManager.GetString("Yes_delete_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, reset it.
        /// </summary>
        public static string Yes_reset_it {
            get {
                return ResourceManager.GetString("Yes_reset_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won&apos;t be able to revert this.
        /// </summary>
        public static string You_wont_be_able_to_revert_this {
            get {
                return ResourceManager.GetString("You_wont_be_able_to_revert_this", resourceCulture);
            }
        }
    }
}
