//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPWA.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPWA.Common.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account locked out.
        /// </summary>
        public static string Account_locked_out {
            get {
                return ResourceManager.GetString("Account_locked_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add city.
        /// </summary>
        public static string Add_city {
            get {
                return ResourceManager.GetString("Add_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add company.
        /// </summary>
        public static string Add_company {
            get {
                return ResourceManager.GetString("Add_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add country.
        /// </summary>
        public static string Add_country {
            get {
                return ResourceManager.GetString("Add_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add currency.
        /// </summary>
        public static string Add_currency {
            get {
                return ResourceManager.GetString("Add_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to add an item.
        /// </summary>
        public static string Add_error {
            get {
                return ResourceManager.GetString("Add_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add language.
        /// </summary>
        public static string Add_language {
            get {
                return ResourceManager.GetString("Add_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add role.
        /// </summary>
        public static string Add_role {
            get {
                return ResourceManager.GetString("Add_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added item.
        /// </summary>
        public static string Add_success {
            get {
                return ResourceManager.GetString("Add_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ticket.
        /// </summary>
        public static string Add_ticket {
            get {
                return ResourceManager.GetString("Add_ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure.
        /// </summary>
        public static string Are_you_sure {
            get {
                return ResourceManager.GetString("Are you sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth settings.
        /// </summary>
        public static string Auth_settings {
            get {
                return ResourceManager.GetString("Auth_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPWA.
        /// </summary>
        public static string BPWA {
            get {
                return ResourceManager.GetString("BPWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug.
        /// </summary>
        public static string Bug {
            get {
                return ResourceManager.GetString("Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an option.
        /// </summary>
        public static string Choose_an_option {
            get {
                return ResourceManager.GetString("Choose_an_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities management.
        /// </summary>
        public static string CitiesManagement {
            get {
                return ResourceManager.GetString("CitiesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filters.
        /// </summary>
        public static string Clear_filters {
            get {
                return ResourceManager.GetString("Clear_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies management.
        /// </summary>
        public static string CompaniesManagement {
            get {
                return ResourceManager.GetString("CompaniesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrency_failure.
        /// </summary>
        public static string Concurrency_failure {
            get {
                return ResourceManager.GetString("Concurrency_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries management.
        /// </summary>
        public static string CountriesManagement {
            get {
                return ResourceManager.GetString("CountriesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies management.
        /// </summary>
        public static string CurrenciesManagement {
            get {
                return ResourceManager.GetString("CurrenciesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default_error.
        /// </summary>
        public static string Default_error {
            get {
                return ResourceManager.GetString("Default_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to delete an item.
        /// </summary>
        public static string Delete_error {
            get {
                return ResourceManager.GetString("Delete_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted an item.
        /// </summary>
        public static string Delete_success {
            get {
                return ResourceManager.GetString("Delete_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying.
        /// </summary>
        public static string Displaying {
            get {
                return ResourceManager.GetString("Displaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate_email.
        /// </summary>
        public static string Duplicate_email {
            get {
                return ResourceManager.GetString("Duplicate_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate_role_name.
        /// </summary>
        public static string Duplicate_role_name {
            get {
                return ResourceManager.GetString("Duplicate_role_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate_user_name.
        /// </summary>
        public static string Duplicate_user_name {
            get {
                return ResourceManager.GetString("Duplicate_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit city.
        /// </summary>
        public static string Edit_city {
            get {
                return ResourceManager.GetString("Edit_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit company.
        /// </summary>
        public static string Edit_company {
            get {
                return ResourceManager.GetString("Edit_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit country.
        /// </summary>
        public static string Edit_country {
            get {
                return ResourceManager.GetString("Edit_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit currency.
        /// </summary>
        public static string Edit_currency {
            get {
                return ResourceManager.GetString("Edit_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to edit an item.
        /// </summary>
        public static string Edit_error {
            get {
                return ResourceManager.GetString("Edit_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit language.
        /// </summary>
        public static string Edit_language {
            get {
                return ResourceManager.GetString("Edit_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit role.
        /// </summary>
        public static string Edit_role {
            get {
                return ResourceManager.GetString("Edit_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully edited an item.
        /// </summary>
        public static string Edit_success {
            get {
                return ResourceManager.GetString("Edit_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit ticket.
        /// </summary>
        public static string Edit_ticket {
            get {
                return ResourceManager.GetString("Edit_ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        public static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geolocations.
        /// </summary>
        public static string Geolocations {
            get {
                return ResourceManager.GetString("Geolocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid_email.
        /// </summary>
        public static string Invalid_email {
            get {
                return ResourceManager.GetString("Invalid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid_role_name.
        /// </summary>
        public static string Invalid_role_name {
            get {
                return ResourceManager.GetString("Invalid_role_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid_token.
        /// </summary>
        public static string Invalid_token {
            get {
                return ResourceManager.GetString("Invalid_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid_user_name.
        /// </summary>
        public static string Invalid_user_name {
            get {
                return ResourceManager.GetString("Invalid_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string Invalid_username_or_password {
            get {
                return ResourceManager.GetString("Invalid_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages management.
        /// </summary>
        public static string LanguagesManagement {
            get {
                return ResourceManager.GetString("LanguagesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login already associated.
        /// </summary>
        public static string Login_already_associated {
            get {
                return ResourceManager.GetString("Login_already_associated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login not allowed.
        /// </summary>
        public static string Login_not_allowed {
            get {
                return ResourceManager.GetString("Login_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two factor authentication required.
        /// </summary>
        public static string Login_required_two_factor {
            get {
                return ResourceManager.GetString("Login_required_two_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More_pages.
        /// </summary>
        public static string More_pages {
            get {
                return ResourceManager.GetString("More_pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New record.
        /// </summary>
        public static string New_record {
            get {
                return ResourceManager.GetString("New_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        public static string No_records_found {
            get {
                return ResourceManager.GetString("No_records_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number.
        /// </summary>
        public static string Page_number {
            get {
                return ResourceManager.GetString("Page_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password mismatch.
        /// </summary>
        public static string Password_mismatch {
            get {
                return ResourceManager.GetString("Password_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password requires_digit.
        /// </summary>
        public static string Password_requires_digit {
            get {
                return ResourceManager.GetString("Password_requires_digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password requires_lower.
        /// </summary>
        public static string Password_requires_lower {
            get {
                return ResourceManager.GetString("Password_requires_lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password requires_non_alphanumeric.
        /// </summary>
        public static string Password_requires_non_alphanumeric {
            get {
                return ResourceManager.GetString("Password_requires_non_alphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password requires_unique_chars.
        /// </summary>
        public static string Password_requires_unique_chars {
            get {
                return ResourceManager.GetString("Password_requires_unique_chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password requires_upper.
        /// </summary>
        public static string Password_requires_upper {
            get {
                return ResourceManager.GetString("Password_requires_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password too short.
        /// </summary>
        public static string Password_too_short {
            get {
                return ResourceManager.GetString("Password_too_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string Please_wait {
            get {
                return ResourceManager.GetString("Please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been deleted.
        /// </summary>
        public static string Record_has_been_deleted {
            get {
                return ResourceManager.GetString("Record_has_been_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code redemption failed.
        /// </summary>
        public static string Recovery_code_redemption_failed {
            get {
                return ResourceManager.GetString("Recovery_code_redemption_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Required_field {
            get {
                return ResourceManager.GetString("Required_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles management.
        /// </summary>
        public static string RolesManagement {
            get {
                return ResourceManager.GetString("RolesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and continue.
        /// </summary>
        public static string Save_and_continue {
            get {
                return ResourceManager.GetString("Save_and_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select app claim.
        /// </summary>
        public static string Select_app_claim {
            get {
                return ResourceManager.GetString("Select_app_claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select country.
        /// </summary>
        public static string Select_country {
            get {
                return ResourceManager.GetString("Select_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select currency.
        /// </summary>
        public static string Select_currency {
            get {
                return ResourceManager.GetString("Select_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string Select_language {
            get {
                return ResourceManager.GetString("Select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select page size.
        /// </summary>
        public static string Select_page_size {
            get {
                return ResourceManager.GetString("Select_page_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ticket status.
        /// </summary>
        public static string Select_ticket_status {
            get {
                return ResourceManager.GetString("Select_ticket_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ticket type.
        /// </summary>
        public static string Select_ticket_type {
            get {
                return ResourceManager.GetString("Select_ticket_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Sign_in {
            get {
                return ResourceManager.GetString("Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System settings.
        /// </summary>
        public static string System_settings {
            get {
                return ResourceManager.GetString("System_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket status.
        /// </summary>
        public static string Ticket_status {
            get {
                return ResourceManager.GetString("Ticket_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket type.
        /// </summary>
        public static string Ticket_type {
            get {
                return ResourceManager.GetString("Ticket_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets management.
        /// </summary>
        public static string TicketsManagement {
            get {
                return ResourceManager.GetString("TicketsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update role.
        /// </summary>
        public static string Update_role {
            get {
                return ResourceManager.GetString("Update role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ticket.
        /// </summary>
        public static string Update_ticket {
            get {
                return ResourceManager.GetString("Update_ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has password.
        /// </summary>
        public static string User_already_has_password {
            get {
                return ResourceManager.GetString("User_already_has_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already in role.
        /// </summary>
        public static string User_already_in_role {
            get {
                return ResourceManager.GetString("User_already_in_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User lockout not enabled.
        /// </summary>
        public static string User_lockout_not_enabled {
            get {
                return ResourceManager.GetString("User_lockout_not_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email.
        /// </summary>
        public static string User_name_or_email {
            get {
                return ResourceManager.GetString("User_name_or_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email invalid.
        /// </summary>
        public static string User_name_or_email_invalid {
            get {
                return ResourceManager.GetString("User_name_or_email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not in role.
        /// </summary>
        public static string User_not_in_role {
            get {
                return ResourceManager.GetString("User_not_in_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete it.
        /// </summary>
        public static string Yes_delete_it {
            get {
                return ResourceManager.GetString("Yes_delete_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won&apos;t be able to revert this.
        /// </summary>
        public static string You_wont_be_able_to_revert_this {
            get {
                return ResourceManager.GetString("You_wont_be_able_to_revert_this", resourceCulture);
            }
        }
    }
}
